# Generated by Django 3.2.9 on 2021-12-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210720_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='reviews',
        ),
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data',
            name='height',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sex',
        ),
    ]
